// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface ClientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Client)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientId = 1;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 1;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>repeated .StockInfo stocks = 2;</code>
   */
  java.util.List<rs.raf.pds.v5.z2.gRPC.StockInfo> 
      getStocksList();
  /**
   * <code>repeated .StockInfo stocks = 2;</code>
   */
  rs.raf.pds.v5.z2.gRPC.StockInfo getStocks(int index);
  /**
   * <code>repeated .StockInfo stocks = 2;</code>
   */
  int getStocksCount();
  /**
   * <code>repeated .StockInfo stocks = 2;</code>
   */
  java.util.List<? extends rs.raf.pds.v5.z2.gRPC.StockInfoOrBuilder> 
      getStocksOrBuilderList();
  /**
   * <code>repeated .StockInfo stocks = 2;</code>
   */
  rs.raf.pds.v5.z2.gRPC.StockInfoOrBuilder getStocksOrBuilder(
      int index);
}
