// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface IspitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ispit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sifra = 1;</code>
   * @return The sifra.
   */
  java.lang.String getSifra();
  /**
   * <code>string sifra = 1;</code>
   * @return The bytes for sifra.
   */
  com.google.protobuf.ByteString
      getSifraBytes();

  /**
   * <code>string sifP = 2;</code>
   * @return The sifP.
   */
  java.lang.String getSifP();
  /**
   * <code>string sifP = 2;</code>
   * @return The bytes for sifP.
   */
  com.google.protobuf.ByteString
      getSifPBytes();
}
