// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package rs.raf.pds.v5.z2.gRPC;

/**
 * Protobuf type {@code IspitIzvestaj}
 */
public final class IspitIzvestaj extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:IspitIzvestaj)
    IspitIzvestajOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IspitIzvestaj.newBuilder() to construct.
  private IspitIzvestaj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IspitIzvestaj() {
    sifIsp_ = "";
    nazivP_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IspitIzvestaj();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rs.raf.pds.v5.z2.gRPC.StudentServiceOuterClass.internal_static_IspitIzvestaj_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rs.raf.pds.v5.z2.gRPC.StudentServiceOuterClass.internal_static_IspitIzvestaj_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rs.raf.pds.v5.z2.gRPC.IspitIzvestaj.class, rs.raf.pds.v5.z2.gRPC.IspitIzvestaj.Builder.class);
  }

  public static final int SIFISP_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sifIsp_ = "";
  /**
   * <code>string sifIsp = 1;</code>
   * @return The sifIsp.
   */
  @java.lang.Override
  public java.lang.String getSifIsp() {
    java.lang.Object ref = sifIsp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sifIsp_ = s;
      return s;
    }
  }
  /**
   * <code>string sifIsp = 1;</code>
   * @return The bytes for sifIsp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSifIspBytes() {
    java.lang.Object ref = sifIsp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sifIsp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAZIVP_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nazivP_ = "";
  /**
   * <code>string nazivP = 2;</code>
   * @return The nazivP.
   */
  @java.lang.Override
  public java.lang.String getNazivP() {
    java.lang.Object ref = nazivP_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nazivP_ = s;
      return s;
    }
  }
  /**
   * <code>string nazivP = 2;</code>
   * @return The bytes for nazivP.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNazivPBytes() {
    java.lang.Object ref = nazivP_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nazivP_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROKMESEC_FIELD_NUMBER = 3;
  private int rokMesec_ = 0;
  /**
   * <code>int32 rokMesec = 3;</code>
   * @return The rokMesec.
   */
  @java.lang.Override
  public int getRokMesec() {
    return rokMesec_;
  }

  public static final int ROKGODINA_FIELD_NUMBER = 4;
  private int rokGodina_ = 0;
  /**
   * <code>int32 rokGodina = 4;</code>
   * @return The rokGodina.
   */
  @java.lang.Override
  public int getRokGodina() {
    return rokGodina_;
  }

  public static final int POLOZILO_FIELD_NUMBER = 5;
  private int polozilo_ = 0;
  /**
   * <code>int32 polozilo = 5;</code>
   * @return The polozilo.
   */
  @java.lang.Override
  public int getPolozilo() {
    return polozilo_;
  }

  public static final int PROSOCENA_FIELD_NUMBER = 6;
  private double prosOcena_ = 0D;
  /**
   * <code>double prosOcena = 6;</code>
   * @return The prosOcena.
   */
  @java.lang.Override
  public double getProsOcena() {
    return prosOcena_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sifIsp_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sifIsp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nazivP_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nazivP_);
    }
    if (rokMesec_ != 0) {
      output.writeInt32(3, rokMesec_);
    }
    if (rokGodina_ != 0) {
      output.writeInt32(4, rokGodina_);
    }
    if (polozilo_ != 0) {
      output.writeInt32(5, polozilo_);
    }
    if (java.lang.Double.doubleToRawLongBits(prosOcena_) != 0) {
      output.writeDouble(6, prosOcena_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sifIsp_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sifIsp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nazivP_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nazivP_);
    }
    if (rokMesec_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, rokMesec_);
    }
    if (rokGodina_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, rokGodina_);
    }
    if (polozilo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, polozilo_);
    }
    if (java.lang.Double.doubleToRawLongBits(prosOcena_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, prosOcena_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rs.raf.pds.v5.z2.gRPC.IspitIzvestaj)) {
      return super.equals(obj);
    }
    rs.raf.pds.v5.z2.gRPC.IspitIzvestaj other = (rs.raf.pds.v5.z2.gRPC.IspitIzvestaj) obj;

    if (!getSifIsp()
        .equals(other.getSifIsp())) return false;
    if (!getNazivP()
        .equals(other.getNazivP())) return false;
    if (getRokMesec()
        != other.getRokMesec()) return false;
    if (getRokGodina()
        != other.getRokGodina()) return false;
    if (getPolozilo()
        != other.getPolozilo()) return false;
    if (java.lang.Double.doubleToLongBits(getProsOcena())
        != java.lang.Double.doubleToLongBits(
            other.getProsOcena())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SIFISP_FIELD_NUMBER;
    hash = (53 * hash) + getSifIsp().hashCode();
    hash = (37 * hash) + NAZIVP_FIELD_NUMBER;
    hash = (53 * hash) + getNazivP().hashCode();
    hash = (37 * hash) + ROKMESEC_FIELD_NUMBER;
    hash = (53 * hash) + getRokMesec();
    hash = (37 * hash) + ROKGODINA_FIELD_NUMBER;
    hash = (53 * hash) + getRokGodina();
    hash = (37 * hash) + POLOZILO_FIELD_NUMBER;
    hash = (53 * hash) + getPolozilo();
    hash = (37 * hash) + PROSOCENA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getProsOcena()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rs.raf.pds.v5.z2.gRPC.IspitIzvestaj parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.IspitIzvestaj parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.IspitIzvestaj parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.IspitIzvestaj parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.IspitIzvestaj parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.IspitIzvestaj parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.IspitIzvestaj parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.IspitIzvestaj parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.IspitIzvestaj parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.IspitIzvestaj parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.IspitIzvestaj parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.IspitIzvestaj parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rs.raf.pds.v5.z2.gRPC.IspitIzvestaj prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code IspitIzvestaj}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:IspitIzvestaj)
      rs.raf.pds.v5.z2.gRPC.IspitIzvestajOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.raf.pds.v5.z2.gRPC.StudentServiceOuterClass.internal_static_IspitIzvestaj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.raf.pds.v5.z2.gRPC.StudentServiceOuterClass.internal_static_IspitIzvestaj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.raf.pds.v5.z2.gRPC.IspitIzvestaj.class, rs.raf.pds.v5.z2.gRPC.IspitIzvestaj.Builder.class);
    }

    // Construct using rs.raf.pds.v5.z2.gRPC.IspitIzvestaj.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sifIsp_ = "";
      nazivP_ = "";
      rokMesec_ = 0;
      rokGodina_ = 0;
      polozilo_ = 0;
      prosOcena_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rs.raf.pds.v5.z2.gRPC.StudentServiceOuterClass.internal_static_IspitIzvestaj_descriptor;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.IspitIzvestaj getDefaultInstanceForType() {
      return rs.raf.pds.v5.z2.gRPC.IspitIzvestaj.getDefaultInstance();
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.IspitIzvestaj build() {
      rs.raf.pds.v5.z2.gRPC.IspitIzvestaj result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.IspitIzvestaj buildPartial() {
      rs.raf.pds.v5.z2.gRPC.IspitIzvestaj result = new rs.raf.pds.v5.z2.gRPC.IspitIzvestaj(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(rs.raf.pds.v5.z2.gRPC.IspitIzvestaj result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sifIsp_ = sifIsp_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.nazivP_ = nazivP_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.rokMesec_ = rokMesec_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.rokGodina_ = rokGodina_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.polozilo_ = polozilo_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.prosOcena_ = prosOcena_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rs.raf.pds.v5.z2.gRPC.IspitIzvestaj) {
        return mergeFrom((rs.raf.pds.v5.z2.gRPC.IspitIzvestaj)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rs.raf.pds.v5.z2.gRPC.IspitIzvestaj other) {
      if (other == rs.raf.pds.v5.z2.gRPC.IspitIzvestaj.getDefaultInstance()) return this;
      if (!other.getSifIsp().isEmpty()) {
        sifIsp_ = other.sifIsp_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getNazivP().isEmpty()) {
        nazivP_ = other.nazivP_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getRokMesec() != 0) {
        setRokMesec(other.getRokMesec());
      }
      if (other.getRokGodina() != 0) {
        setRokGodina(other.getRokGodina());
      }
      if (other.getPolozilo() != 0) {
        setPolozilo(other.getPolozilo());
      }
      if (other.getProsOcena() != 0D) {
        setProsOcena(other.getProsOcena());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sifIsp_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              nazivP_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              rokMesec_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              rokGodina_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              polozilo_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 49: {
              prosOcena_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sifIsp_ = "";
    /**
     * <code>string sifIsp = 1;</code>
     * @return The sifIsp.
     */
    public java.lang.String getSifIsp() {
      java.lang.Object ref = sifIsp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sifIsp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sifIsp = 1;</code>
     * @return The bytes for sifIsp.
     */
    public com.google.protobuf.ByteString
        getSifIspBytes() {
      java.lang.Object ref = sifIsp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sifIsp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sifIsp = 1;</code>
     * @param value The sifIsp to set.
     * @return This builder for chaining.
     */
    public Builder setSifIsp(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sifIsp_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string sifIsp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSifIsp() {
      sifIsp_ = getDefaultInstance().getSifIsp();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string sifIsp = 1;</code>
     * @param value The bytes for sifIsp to set.
     * @return This builder for chaining.
     */
    public Builder setSifIspBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sifIsp_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object nazivP_ = "";
    /**
     * <code>string nazivP = 2;</code>
     * @return The nazivP.
     */
    public java.lang.String getNazivP() {
      java.lang.Object ref = nazivP_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nazivP_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nazivP = 2;</code>
     * @return The bytes for nazivP.
     */
    public com.google.protobuf.ByteString
        getNazivPBytes() {
      java.lang.Object ref = nazivP_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nazivP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nazivP = 2;</code>
     * @param value The nazivP to set.
     * @return This builder for chaining.
     */
    public Builder setNazivP(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nazivP_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string nazivP = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNazivP() {
      nazivP_ = getDefaultInstance().getNazivP();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string nazivP = 2;</code>
     * @param value The bytes for nazivP to set.
     * @return This builder for chaining.
     */
    public Builder setNazivPBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nazivP_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int rokMesec_ ;
    /**
     * <code>int32 rokMesec = 3;</code>
     * @return The rokMesec.
     */
    @java.lang.Override
    public int getRokMesec() {
      return rokMesec_;
    }
    /**
     * <code>int32 rokMesec = 3;</code>
     * @param value The rokMesec to set.
     * @return This builder for chaining.
     */
    public Builder setRokMesec(int value) {

      rokMesec_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rokMesec = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRokMesec() {
      bitField0_ = (bitField0_ & ~0x00000004);
      rokMesec_ = 0;
      onChanged();
      return this;
    }

    private int rokGodina_ ;
    /**
     * <code>int32 rokGodina = 4;</code>
     * @return The rokGodina.
     */
    @java.lang.Override
    public int getRokGodina() {
      return rokGodina_;
    }
    /**
     * <code>int32 rokGodina = 4;</code>
     * @param value The rokGodina to set.
     * @return This builder for chaining.
     */
    public Builder setRokGodina(int value) {

      rokGodina_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rokGodina = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRokGodina() {
      bitField0_ = (bitField0_ & ~0x00000008);
      rokGodina_ = 0;
      onChanged();
      return this;
    }

    private int polozilo_ ;
    /**
     * <code>int32 polozilo = 5;</code>
     * @return The polozilo.
     */
    @java.lang.Override
    public int getPolozilo() {
      return polozilo_;
    }
    /**
     * <code>int32 polozilo = 5;</code>
     * @param value The polozilo to set.
     * @return This builder for chaining.
     */
    public Builder setPolozilo(int value) {

      polozilo_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 polozilo = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPolozilo() {
      bitField0_ = (bitField0_ & ~0x00000010);
      polozilo_ = 0;
      onChanged();
      return this;
    }

    private double prosOcena_ ;
    /**
     * <code>double prosOcena = 6;</code>
     * @return The prosOcena.
     */
    @java.lang.Override
    public double getProsOcena() {
      return prosOcena_;
    }
    /**
     * <code>double prosOcena = 6;</code>
     * @param value The prosOcena to set.
     * @return This builder for chaining.
     */
    public Builder setProsOcena(double value) {

      prosOcena_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>double prosOcena = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearProsOcena() {
      bitField0_ = (bitField0_ & ~0x00000020);
      prosOcena_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:IspitIzvestaj)
  }

  // @@protoc_insertion_point(class_scope:IspitIzvestaj)
  private static final rs.raf.pds.v5.z2.gRPC.IspitIzvestaj DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rs.raf.pds.v5.z2.gRPC.IspitIzvestaj();
  }

  public static rs.raf.pds.v5.z2.gRPC.IspitIzvestaj getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IspitIzvestaj>
      PARSER = new com.google.protobuf.AbstractParser<IspitIzvestaj>() {
    @java.lang.Override
    public IspitIzvestaj parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<IspitIzvestaj> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IspitIzvestaj> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.IspitIzvestaj getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

