// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface IspitIzvestajOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IspitIzvestaj)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sifIsp = 1;</code>
   * @return The sifIsp.
   */
  java.lang.String getSifIsp();
  /**
   * <code>string sifIsp = 1;</code>
   * @return The bytes for sifIsp.
   */
  com.google.protobuf.ByteString
      getSifIspBytes();

  /**
   * <code>string nazivP = 2;</code>
   * @return The nazivP.
   */
  java.lang.String getNazivP();
  /**
   * <code>string nazivP = 2;</code>
   * @return The bytes for nazivP.
   */
  com.google.protobuf.ByteString
      getNazivPBytes();

  /**
   * <code>int32 rokMesec = 3;</code>
   * @return The rokMesec.
   */
  int getRokMesec();

  /**
   * <code>int32 rokGodina = 4;</code>
   * @return The rokGodina.
   */
  int getRokGodina();

  /**
   * <code>int32 polozilo = 5;</code>
   * @return The polozilo.
   */
  int getPolozilo();

  /**
   * <code>double prosOcena = 6;</code>
   * @return The prosOcena.
   */
  double getProsOcena();
}
