// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface OcenaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ocena)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sifIsp = 1;</code>
   * @return The sifIsp.
   */
  java.lang.String getSifIsp();
  /**
   * <code>string sifIsp = 1;</code>
   * @return The bytes for sifIsp.
   */
  com.google.protobuf.ByteString
      getSifIspBytes();

  /**
   * <code>string sifPred = 2;</code>
   * @return The sifPred.
   */
  java.lang.String getSifPred();
  /**
   * <code>string sifPred = 2;</code>
   * @return The bytes for sifPred.
   */
  com.google.protobuf.ByteString
      getSifPredBytes();

  /**
   * <code>string sifStud = 3;</code>
   * @return The sifStud.
   */
  java.lang.String getSifStud();
  /**
   * <code>string sifStud = 3;</code>
   * @return The bytes for sifStud.
   */
  com.google.protobuf.ByteString
      getSifStudBytes();

  /**
   * <code>int32 ocena = 4;</code>
   * @return The ocena.
   */
  int getOcena();
}
