// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package rs.raf.pds.v5.z2.gRPC;

/**
 * Protobuf type {@code Ocena}
 */
public final class Ocena extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Ocena)
    OcenaOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Ocena.newBuilder() to construct.
  private Ocena(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Ocena() {
    sifIsp_ = "";
    sifPred_ = "";
    sifStud_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Ocena();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rs.raf.pds.v5.z2.gRPC.StudentServiceOuterClass.internal_static_Ocena_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rs.raf.pds.v5.z2.gRPC.StudentServiceOuterClass.internal_static_Ocena_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rs.raf.pds.v5.z2.gRPC.Ocena.class, rs.raf.pds.v5.z2.gRPC.Ocena.Builder.class);
  }

  public static final int SIFISP_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sifIsp_ = "";
  /**
   * <code>string sifIsp = 1;</code>
   * @return The sifIsp.
   */
  @java.lang.Override
  public java.lang.String getSifIsp() {
    java.lang.Object ref = sifIsp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sifIsp_ = s;
      return s;
    }
  }
  /**
   * <code>string sifIsp = 1;</code>
   * @return The bytes for sifIsp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSifIspBytes() {
    java.lang.Object ref = sifIsp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sifIsp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIFPRED_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sifPred_ = "";
  /**
   * <code>string sifPred = 2;</code>
   * @return The sifPred.
   */
  @java.lang.Override
  public java.lang.String getSifPred() {
    java.lang.Object ref = sifPred_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sifPred_ = s;
      return s;
    }
  }
  /**
   * <code>string sifPred = 2;</code>
   * @return The bytes for sifPred.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSifPredBytes() {
    java.lang.Object ref = sifPred_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sifPred_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIFSTUD_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sifStud_ = "";
  /**
   * <code>string sifStud = 3;</code>
   * @return The sifStud.
   */
  @java.lang.Override
  public java.lang.String getSifStud() {
    java.lang.Object ref = sifStud_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sifStud_ = s;
      return s;
    }
  }
  /**
   * <code>string sifStud = 3;</code>
   * @return The bytes for sifStud.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSifStudBytes() {
    java.lang.Object ref = sifStud_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sifStud_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OCENA_FIELD_NUMBER = 4;
  private int ocena_ = 0;
  /**
   * <code>int32 ocena = 4;</code>
   * @return The ocena.
   */
  @java.lang.Override
  public int getOcena() {
    return ocena_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sifIsp_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sifIsp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sifPred_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sifPred_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sifStud_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sifStud_);
    }
    if (ocena_ != 0) {
      output.writeInt32(4, ocena_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sifIsp_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sifIsp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sifPred_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sifPred_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sifStud_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sifStud_);
    }
    if (ocena_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, ocena_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rs.raf.pds.v5.z2.gRPC.Ocena)) {
      return super.equals(obj);
    }
    rs.raf.pds.v5.z2.gRPC.Ocena other = (rs.raf.pds.v5.z2.gRPC.Ocena) obj;

    if (!getSifIsp()
        .equals(other.getSifIsp())) return false;
    if (!getSifPred()
        .equals(other.getSifPred())) return false;
    if (!getSifStud()
        .equals(other.getSifStud())) return false;
    if (getOcena()
        != other.getOcena()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SIFISP_FIELD_NUMBER;
    hash = (53 * hash) + getSifIsp().hashCode();
    hash = (37 * hash) + SIFPRED_FIELD_NUMBER;
    hash = (53 * hash) + getSifPred().hashCode();
    hash = (37 * hash) + SIFSTUD_FIELD_NUMBER;
    hash = (53 * hash) + getSifStud().hashCode();
    hash = (37 * hash) + OCENA_FIELD_NUMBER;
    hash = (53 * hash) + getOcena();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rs.raf.pds.v5.z2.gRPC.Ocena parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.Ocena parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.Ocena parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.Ocena parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.Ocena parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.Ocena parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.Ocena parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.Ocena parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.Ocena parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.Ocena parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.Ocena parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.Ocena parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rs.raf.pds.v5.z2.gRPC.Ocena prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Ocena}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Ocena)
      rs.raf.pds.v5.z2.gRPC.OcenaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.raf.pds.v5.z2.gRPC.StudentServiceOuterClass.internal_static_Ocena_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.raf.pds.v5.z2.gRPC.StudentServiceOuterClass.internal_static_Ocena_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.raf.pds.v5.z2.gRPC.Ocena.class, rs.raf.pds.v5.z2.gRPC.Ocena.Builder.class);
    }

    // Construct using rs.raf.pds.v5.z2.gRPC.Ocena.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sifIsp_ = "";
      sifPred_ = "";
      sifStud_ = "";
      ocena_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rs.raf.pds.v5.z2.gRPC.StudentServiceOuterClass.internal_static_Ocena_descriptor;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.Ocena getDefaultInstanceForType() {
      return rs.raf.pds.v5.z2.gRPC.Ocena.getDefaultInstance();
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.Ocena build() {
      rs.raf.pds.v5.z2.gRPC.Ocena result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.Ocena buildPartial() {
      rs.raf.pds.v5.z2.gRPC.Ocena result = new rs.raf.pds.v5.z2.gRPC.Ocena(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(rs.raf.pds.v5.z2.gRPC.Ocena result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sifIsp_ = sifIsp_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sifPred_ = sifPred_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sifStud_ = sifStud_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.ocena_ = ocena_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rs.raf.pds.v5.z2.gRPC.Ocena) {
        return mergeFrom((rs.raf.pds.v5.z2.gRPC.Ocena)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rs.raf.pds.v5.z2.gRPC.Ocena other) {
      if (other == rs.raf.pds.v5.z2.gRPC.Ocena.getDefaultInstance()) return this;
      if (!other.getSifIsp().isEmpty()) {
        sifIsp_ = other.sifIsp_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSifPred().isEmpty()) {
        sifPred_ = other.sifPred_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSifStud().isEmpty()) {
        sifStud_ = other.sifStud_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getOcena() != 0) {
        setOcena(other.getOcena());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sifIsp_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              sifPred_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              sifStud_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              ocena_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sifIsp_ = "";
    /**
     * <code>string sifIsp = 1;</code>
     * @return The sifIsp.
     */
    public java.lang.String getSifIsp() {
      java.lang.Object ref = sifIsp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sifIsp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sifIsp = 1;</code>
     * @return The bytes for sifIsp.
     */
    public com.google.protobuf.ByteString
        getSifIspBytes() {
      java.lang.Object ref = sifIsp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sifIsp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sifIsp = 1;</code>
     * @param value The sifIsp to set.
     * @return This builder for chaining.
     */
    public Builder setSifIsp(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sifIsp_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string sifIsp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSifIsp() {
      sifIsp_ = getDefaultInstance().getSifIsp();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string sifIsp = 1;</code>
     * @param value The bytes for sifIsp to set.
     * @return This builder for chaining.
     */
    public Builder setSifIspBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sifIsp_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object sifPred_ = "";
    /**
     * <code>string sifPred = 2;</code>
     * @return The sifPred.
     */
    public java.lang.String getSifPred() {
      java.lang.Object ref = sifPred_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sifPred_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sifPred = 2;</code>
     * @return The bytes for sifPred.
     */
    public com.google.protobuf.ByteString
        getSifPredBytes() {
      java.lang.Object ref = sifPred_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sifPred_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sifPred = 2;</code>
     * @param value The sifPred to set.
     * @return This builder for chaining.
     */
    public Builder setSifPred(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sifPred_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string sifPred = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSifPred() {
      sifPred_ = getDefaultInstance().getSifPred();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string sifPred = 2;</code>
     * @param value The bytes for sifPred to set.
     * @return This builder for chaining.
     */
    public Builder setSifPredBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sifPred_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object sifStud_ = "";
    /**
     * <code>string sifStud = 3;</code>
     * @return The sifStud.
     */
    public java.lang.String getSifStud() {
      java.lang.Object ref = sifStud_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sifStud_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sifStud = 3;</code>
     * @return The bytes for sifStud.
     */
    public com.google.protobuf.ByteString
        getSifStudBytes() {
      java.lang.Object ref = sifStud_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sifStud_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sifStud = 3;</code>
     * @param value The sifStud to set.
     * @return This builder for chaining.
     */
    public Builder setSifStud(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sifStud_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string sifStud = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSifStud() {
      sifStud_ = getDefaultInstance().getSifStud();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string sifStud = 3;</code>
     * @param value The bytes for sifStud to set.
     * @return This builder for chaining.
     */
    public Builder setSifStudBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sifStud_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int ocena_ ;
    /**
     * <code>int32 ocena = 4;</code>
     * @return The ocena.
     */
    @java.lang.Override
    public int getOcena() {
      return ocena_;
    }
    /**
     * <code>int32 ocena = 4;</code>
     * @param value The ocena to set.
     * @return This builder for chaining.
     */
    public Builder setOcena(int value) {

      ocena_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ocena = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOcena() {
      bitField0_ = (bitField0_ & ~0x00000008);
      ocena_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Ocena)
  }

  // @@protoc_insertion_point(class_scope:Ocena)
  private static final rs.raf.pds.v5.z2.gRPC.Ocena DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rs.raf.pds.v5.z2.gRPC.Ocena();
  }

  public static rs.raf.pds.v5.z2.gRPC.Ocena getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Ocena>
      PARSER = new com.google.protobuf.AbstractParser<Ocena>() {
    @java.lang.Override
    public Ocena parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Ocena> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Ocena> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.Ocena getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

