// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>double pricePerShare = 2;</code>
   * @return The pricePerShare.
   */
  double getPricePerShare();

  /**
   * <code>int32 numShares = 3;</code>
   * @return The numShares.
   */
  int getNumShares();
}
