// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface OrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>bool transaction = 2;</code>
   * @return The transaction.
   */
  boolean getTransaction();

  /**
   * <code>bool failed = 3;</code>
   * @return The failed.
   */
  boolean getFailed();
}
