// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface OrderListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Order offers = 1;</code>
   */
  java.util.List<rs.raf.pds.v5.z2.gRPC.Order> 
      getOffersList();
  /**
   * <code>repeated .Order offers = 1;</code>
   */
  rs.raf.pds.v5.z2.gRPC.Order getOffers(int index);
  /**
   * <code>repeated .Order offers = 1;</code>
   */
  int getOffersCount();
  /**
   * <code>repeated .Order offers = 1;</code>
   */
  java.util.List<? extends rs.raf.pds.v5.z2.gRPC.OrderOrBuilder> 
      getOffersOrBuilderList();
  /**
   * <code>repeated .Order offers = 1;</code>
   */
  rs.raf.pds.v5.z2.gRPC.OrderOrBuilder getOffersOrBuilder(
      int index);
}
