// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface PredmetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Predmet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sifra = 1;</code>
   * @return The sifra.
   */
  java.lang.String getSifra();
  /**
   * <code>string sifra = 1;</code>
   * @return The bytes for sifra.
   */
  com.google.protobuf.ByteString
      getSifraBytes();

  /**
   * <code>string naziv = 2;</code>
   * @return The naziv.
   */
  java.lang.String getNaziv();
  /**
   * <code>string naziv = 2;</code>
   * @return The bytes for naziv.
   */
  com.google.protobuf.ByteString
      getNazivBytes();

  /**
   * <code>int32 godina = 3;</code>
   * @return The godina.
   */
  int getGodina();
}
