// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface StockDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string companyName = 2;</code>
   * @return The companyName.
   */
  java.lang.String getCompanyName();
  /**
   * <code>string companyName = 2;</code>
   * @return The bytes for companyName.
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <code>double priceAtStart = 3;</code>
   * @return The priceAtStart.
   */
  double getPriceAtStart();

  /**
   * <code>double priceChange = 4;</code>
   * @return The priceChange.
   */
  double getPriceChange();

  /**
   * <code>.google.protobuf.Timestamp date = 5;</code>
   * @return Whether the date field is set.
   */
  boolean hasDate();
  /**
   * <code>.google.protobuf.Timestamp date = 5;</code>
   * @return The date.
   */
  com.google.protobuf.Timestamp getDate();
  /**
   * <code>.google.protobuf.Timestamp date = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateOrBuilder();

  /**
   * <pre>
   * Assuming history is a list of price changes
   * </pre>
   *
   * <code>repeated double history = 6;</code>
   * @return A list containing the history.
   */
  java.util.List<java.lang.Double> getHistoryList();
  /**
   * <pre>
   * Assuming history is a list of price changes
   * </pre>
   *
   * <code>repeated double history = 6;</code>
   * @return The count of history.
   */
  int getHistoryCount();
  /**
   * <pre>
   * Assuming history is a list of price changes
   * </pre>
   *
   * <code>repeated double history = 6;</code>
   * @param index The index of the element to return.
   * @return The history at the given index.
   */
  double getHistory(int index);
}
