// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package rs.raf.pds.v5.z2.gRPC;

/**
 * Protobuf type {@code StockInfo}
 */
public final class StockInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:StockInfo)
    StockInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StockInfo.newBuilder() to construct.
  private StockInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StockInfo() {
    symbol_ = "";
    priceChange1H_ = "";
    priceChange24H_ = "";
    priceChange7D_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StockInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rs.raf.pds.v5.z2.gRPC.StudentService.internal_static_StockInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rs.raf.pds.v5.z2.gRPC.StudentService.internal_static_StockInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rs.raf.pds.v5.z2.gRPC.StockInfo.class, rs.raf.pds.v5.z2.gRPC.StockInfo.Builder.class);
  }

  public static final int SYMBOL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object symbol_ = "";
  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENTPRICE_FIELD_NUMBER = 2;
  private double currentPrice_ = 0D;
  /**
   * <code>double currentPrice = 2;</code>
   * @return The currentPrice.
   */
  @java.lang.Override
  public double getCurrentPrice() {
    return currentPrice_;
  }

  public static final int PRICECHANGE1H_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object priceChange1H_ = "";
  /**
   * <code>string priceChange1h = 3;</code>
   * @return The priceChange1h.
   */
  @java.lang.Override
  public java.lang.String getPriceChange1H() {
    java.lang.Object ref = priceChange1H_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      priceChange1H_ = s;
      return s;
    }
  }
  /**
   * <code>string priceChange1h = 3;</code>
   * @return The bytes for priceChange1h.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPriceChange1HBytes() {
    java.lang.Object ref = priceChange1H_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      priceChange1H_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICECHANGE24H_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object priceChange24H_ = "";
  /**
   * <code>string priceChange24h = 4;</code>
   * @return The priceChange24h.
   */
  @java.lang.Override
  public java.lang.String getPriceChange24H() {
    java.lang.Object ref = priceChange24H_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      priceChange24H_ = s;
      return s;
    }
  }
  /**
   * <code>string priceChange24h = 4;</code>
   * @return The bytes for priceChange24h.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPriceChange24HBytes() {
    java.lang.Object ref = priceChange24H_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      priceChange24H_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICECHANGE7D_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object priceChange7D_ = "";
  /**
   * <code>string priceChange7d = 5;</code>
   * @return The priceChange7d.
   */
  @java.lang.Override
  public java.lang.String getPriceChange7D() {
    java.lang.Object ref = priceChange7D_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      priceChange7D_ = s;
      return s;
    }
  }
  /**
   * <code>string priceChange7d = 5;</code>
   * @return The bytes for priceChange7d.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPriceChange7DBytes() {
    java.lang.Object ref = priceChange7D_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      priceChange7D_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbol_);
    }
    if (java.lang.Double.doubleToRawLongBits(currentPrice_) != 0) {
      output.writeDouble(2, currentPrice_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(priceChange1H_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, priceChange1H_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(priceChange24H_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, priceChange24H_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(priceChange7D_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, priceChange7D_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symbol_);
    }
    if (java.lang.Double.doubleToRawLongBits(currentPrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, currentPrice_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(priceChange1H_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, priceChange1H_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(priceChange24H_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, priceChange24H_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(priceChange7D_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, priceChange7D_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rs.raf.pds.v5.z2.gRPC.StockInfo)) {
      return super.equals(obj);
    }
    rs.raf.pds.v5.z2.gRPC.StockInfo other = (rs.raf.pds.v5.z2.gRPC.StockInfo) obj;

    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (java.lang.Double.doubleToLongBits(getCurrentPrice())
        != java.lang.Double.doubleToLongBits(
            other.getCurrentPrice())) return false;
    if (!getPriceChange1H()
        .equals(other.getPriceChange1H())) return false;
    if (!getPriceChange24H()
        .equals(other.getPriceChange24H())) return false;
    if (!getPriceChange7D()
        .equals(other.getPriceChange7D())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (37 * hash) + CURRENTPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCurrentPrice()));
    hash = (37 * hash) + PRICECHANGE1H_FIELD_NUMBER;
    hash = (53 * hash) + getPriceChange1H().hashCode();
    hash = (37 * hash) + PRICECHANGE24H_FIELD_NUMBER;
    hash = (53 * hash) + getPriceChange24H().hashCode();
    hash = (37 * hash) + PRICECHANGE7D_FIELD_NUMBER;
    hash = (53 * hash) + getPriceChange7D().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rs.raf.pds.v5.z2.gRPC.StockInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rs.raf.pds.v5.z2.gRPC.StockInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code StockInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:StockInfo)
      rs.raf.pds.v5.z2.gRPC.StockInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.raf.pds.v5.z2.gRPC.StudentService.internal_static_StockInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.raf.pds.v5.z2.gRPC.StudentService.internal_static_StockInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.raf.pds.v5.z2.gRPC.StockInfo.class, rs.raf.pds.v5.z2.gRPC.StockInfo.Builder.class);
    }

    // Construct using rs.raf.pds.v5.z2.gRPC.StockInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      symbol_ = "";
      currentPrice_ = 0D;
      priceChange1H_ = "";
      priceChange24H_ = "";
      priceChange7D_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rs.raf.pds.v5.z2.gRPC.StudentService.internal_static_StockInfo_descriptor;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.StockInfo getDefaultInstanceForType() {
      return rs.raf.pds.v5.z2.gRPC.StockInfo.getDefaultInstance();
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.StockInfo build() {
      rs.raf.pds.v5.z2.gRPC.StockInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.StockInfo buildPartial() {
      rs.raf.pds.v5.z2.gRPC.StockInfo result = new rs.raf.pds.v5.z2.gRPC.StockInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(rs.raf.pds.v5.z2.gRPC.StockInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.symbol_ = symbol_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.currentPrice_ = currentPrice_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.priceChange1H_ = priceChange1H_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.priceChange24H_ = priceChange24H_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.priceChange7D_ = priceChange7D_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rs.raf.pds.v5.z2.gRPC.StockInfo) {
        return mergeFrom((rs.raf.pds.v5.z2.gRPC.StockInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rs.raf.pds.v5.z2.gRPC.StockInfo other) {
      if (other == rs.raf.pds.v5.z2.gRPC.StockInfo.getDefaultInstance()) return this;
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getCurrentPrice() != 0D) {
        setCurrentPrice(other.getCurrentPrice());
      }
      if (!other.getPriceChange1H().isEmpty()) {
        priceChange1H_ = other.priceChange1H_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getPriceChange24H().isEmpty()) {
        priceChange24H_ = other.priceChange24H_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getPriceChange7D().isEmpty()) {
        priceChange7D_ = other.priceChange7D_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              symbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 17: {
              currentPrice_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 26: {
              priceChange1H_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              priceChange24H_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              priceChange7D_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object symbol_ = "";
    /**
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string symbol = 1;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      symbol_ = getDefaultInstance().getSymbol();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 1;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private double currentPrice_ ;
    /**
     * <code>double currentPrice = 2;</code>
     * @return The currentPrice.
     */
    @java.lang.Override
    public double getCurrentPrice() {
      return currentPrice_;
    }
    /**
     * <code>double currentPrice = 2;</code>
     * @param value The currentPrice to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentPrice(double value) {

      currentPrice_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double currentPrice = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentPrice() {
      bitField0_ = (bitField0_ & ~0x00000002);
      currentPrice_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object priceChange1H_ = "";
    /**
     * <code>string priceChange1h = 3;</code>
     * @return The priceChange1h.
     */
    public java.lang.String getPriceChange1H() {
      java.lang.Object ref = priceChange1H_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        priceChange1H_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string priceChange1h = 3;</code>
     * @return The bytes for priceChange1h.
     */
    public com.google.protobuf.ByteString
        getPriceChange1HBytes() {
      java.lang.Object ref = priceChange1H_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        priceChange1H_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string priceChange1h = 3;</code>
     * @param value The priceChange1h to set.
     * @return This builder for chaining.
     */
    public Builder setPriceChange1H(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      priceChange1H_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string priceChange1h = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPriceChange1H() {
      priceChange1H_ = getDefaultInstance().getPriceChange1H();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string priceChange1h = 3;</code>
     * @param value The bytes for priceChange1h to set.
     * @return This builder for chaining.
     */
    public Builder setPriceChange1HBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      priceChange1H_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object priceChange24H_ = "";
    /**
     * <code>string priceChange24h = 4;</code>
     * @return The priceChange24h.
     */
    public java.lang.String getPriceChange24H() {
      java.lang.Object ref = priceChange24H_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        priceChange24H_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string priceChange24h = 4;</code>
     * @return The bytes for priceChange24h.
     */
    public com.google.protobuf.ByteString
        getPriceChange24HBytes() {
      java.lang.Object ref = priceChange24H_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        priceChange24H_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string priceChange24h = 4;</code>
     * @param value The priceChange24h to set.
     * @return This builder for chaining.
     */
    public Builder setPriceChange24H(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      priceChange24H_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string priceChange24h = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPriceChange24H() {
      priceChange24H_ = getDefaultInstance().getPriceChange24H();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string priceChange24h = 4;</code>
     * @param value The bytes for priceChange24h to set.
     * @return This builder for chaining.
     */
    public Builder setPriceChange24HBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      priceChange24H_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object priceChange7D_ = "";
    /**
     * <code>string priceChange7d = 5;</code>
     * @return The priceChange7d.
     */
    public java.lang.String getPriceChange7D() {
      java.lang.Object ref = priceChange7D_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        priceChange7D_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string priceChange7d = 5;</code>
     * @return The bytes for priceChange7d.
     */
    public com.google.protobuf.ByteString
        getPriceChange7DBytes() {
      java.lang.Object ref = priceChange7D_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        priceChange7D_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string priceChange7d = 5;</code>
     * @param value The priceChange7d to set.
     * @return This builder for chaining.
     */
    public Builder setPriceChange7D(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      priceChange7D_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string priceChange7d = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPriceChange7D() {
      priceChange7D_ = getDefaultInstance().getPriceChange7D();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string priceChange7d = 5;</code>
     * @param value The bytes for priceChange7d to set.
     * @return This builder for chaining.
     */
    public Builder setPriceChange7DBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      priceChange7D_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:StockInfo)
  }

  // @@protoc_insertion_point(class_scope:StockInfo)
  private static final rs.raf.pds.v5.z2.gRPC.StockInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rs.raf.pds.v5.z2.gRPC.StockInfo();
  }

  public static rs.raf.pds.v5.z2.gRPC.StockInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StockInfo>
      PARSER = new com.google.protobuf.AbstractParser<StockInfo>() {
    @java.lang.Override
    public StockInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StockInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StockInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.StockInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

