// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package rs.raf.pds.v5.z2.gRPC;

public final class StudentServiceOuterClass {
  private StudentServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Student_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StudentUpit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StudentUpit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Predmet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Predmet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ispit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ispit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ocena_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ocena_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IspitIzvestaj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IspitIzvestaj_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025student_service.proto\"7\n\007Student\022\017\n\007si" +
      "fStud\030\001 \001(\t\022\013\n\003ime\030\002 \001(\t\022\016\n\006godina\030\003 \001(\005" +
      "\";\n\013StudentUpit\022\017\n\007sifStud\030\001 \001(\t\022\013\n\003ime\030" +
      "\002 \001(\t\022\016\n\006godina\030\003 \001(\005\"7\n\007Predmet\022\r\n\005sifr" +
      "a\030\001 \001(\t\022\r\n\005naziv\030\002 \001(\t\022\016\n\006godina\030\003 \001(\005\"$" +
      "\n\005Ispit\022\r\n\005sifra\030\001 \001(\t\022\014\n\004sifP\030\002 \001(\t\"H\n\005" +
      "Ocena\022\016\n\006sifIsp\030\001 \001(\t\022\017\n\007sifPred\030\002 \001(\t\022\017" +
      "\n\007sifStud\030\003 \001(\t\022\r\n\005ocena\030\004 \001(\005\"y\n\rIspitI" +
      "zvestaj\022\016\n\006sifIsp\030\001 \001(\t\022\016\n\006nazivP\030\002 \001(\t\022" +
      "\020\n\010rokMesec\030\003 \001(\005\022\021\n\trokGodina\030\004 \001(\005\022\020\n\010" +
      "polozilo\030\005 \001(\005\022\021\n\tprosOcena\030\006 \001(\0012\211\001\n\016St" +
      "udentService\022&\n\nGetStudent\022\014.StudentUpit" +
      "\032\010.Student\"\000\022&\n\016GetAllStudents\022\006.Ispit\032\010" +
      ".Student\"\0000\001\022\'\n\tUnosOcena\022\006.Ocena\032\016.Ispi" +
      "tIzvestaj\"\000(\001B\031\n\025rs.raf.pds.v5.z2.gRPCP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Student_descriptor,
        new java.lang.String[] { "SifStud", "Ime", "Godina", });
    internal_static_StudentUpit_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StudentUpit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StudentUpit_descriptor,
        new java.lang.String[] { "SifStud", "Ime", "Godina", });
    internal_static_Predmet_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Predmet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Predmet_descriptor,
        new java.lang.String[] { "Sifra", "Naziv", "Godina", });
    internal_static_Ispit_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Ispit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ispit_descriptor,
        new java.lang.String[] { "Sifra", "SifP", });
    internal_static_Ocena_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Ocena_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ocena_descriptor,
        new java.lang.String[] { "SifIsp", "SifPred", "SifStud", "Ocena", });
    internal_static_IspitIzvestaj_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_IspitIzvestaj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IspitIzvestaj_descriptor,
        new java.lang.String[] { "SifIsp", "NazivP", "RokMesec", "RokGodina", "Polozilo", "ProsOcena", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
