// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package rs.raf.pds.v5.z2.gRPC;

public final class StudentService {
  private StudentService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025student_service.proto\032\037google/protobuf" +
      "/timestamp.proto\"\016\n\014EmptyMessage\"\036\n\014Stoc" +
      "kRequest\022\016\n\006symbol\030\001 \001(\t\"\205\001\n\tStockData\022\016" +
      "\n\006symbol\030\001 \001(\t\022\023\n\013companyName\030\002 \001(\t\022\024\n\014p" +
      "riceAtStart\030\003 \001(\001\022\023\n\013priceChange\030\004 \001(\001\022(" +
      "\n\004date\030\005 \001(\0132\032.google.protobuf.Timestamp" +
      "\"w\n\tStockInfo\022\016\n\006symbol\030\001 \001(\t\022\024\n\014current" +
      "Price\030\002 \001(\001\022\025\n\rpriceChange1h\030\003 \001(\t\022\026\n\016pr" +
      "iceChange24h\030\004 \001(\t\022\025\n\rpriceChange7d\030\005 \001(" +
      "\t\"/\n\nAskRequest\022\016\n\006symbol\030\001 \001(\t\022\021\n\tnumOf" +
      "fers\030\002 \001(\005\"/\n\nBidRequest\022\016\n\006symbol\030\001 \001(\t" +
      "\022\021\n\tnumOffers\030\002 \001(\005\"A\n\005Order\022\016\n\006symbol\030\001" +
      " \001(\t\022\025\n\rpricePerShare\030\002 \001(\001\022\021\n\tnumShares" +
      "\030\003 \001(\0052\356\001\n\024StockExchangeService\022+\n\014GetSt" +
      "ockData\022\r.StockRequest\032\n.StockData\"\000\022.\n\017" +
      "GetAllStockData\022\r.EmptyMessage\032\n.StockDa" +
      "ta0\001\022)\n\014GetAskOffers\022\013.AskRequest\032\n.Stoc" +
      "kData0\001\022)\n\014GetBidOffers\022\013.BidRequest\032\n.S" +
      "tockData0\001\022#\n\nPlaceOrder\022\006.Order\032\r.Empty" +
      "MessageB\031\n\025rs.raf.pds.v5.z2.gRPCP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_EmptyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EmptyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyMessage_descriptor,
        new java.lang.String[] { });
    internal_static_StockRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockRequest_descriptor,
        new java.lang.String[] { "Symbol", });
    internal_static_StockData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StockData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockData_descriptor,
        new java.lang.String[] { "Symbol", "CompanyName", "PriceAtStart", "PriceChange", "Date", });
    internal_static_StockInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_StockInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockInfo_descriptor,
        new java.lang.String[] { "Symbol", "CurrentPrice", "PriceChange1H", "PriceChange24H", "PriceChange7D", });
    internal_static_AskRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_AskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AskRequest_descriptor,
        new java.lang.String[] { "Symbol", "NumOffers", });
    internal_static_BidRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_BidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidRequest_descriptor,
        new java.lang.String[] { "Symbol", "NumOffers", });
    internal_static_Order_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Order_descriptor,
        new java.lang.String[] { "Symbol", "PricePerShare", "NumShares", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
