// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sifStud = 1;</code>
   * @return The sifStud.
   */
  java.lang.String getSifStud();
  /**
   * <code>string sifStud = 1;</code>
   * @return The bytes for sifStud.
   */
  com.google.protobuf.ByteString
      getSifStudBytes();

  /**
   * <code>string ime = 2;</code>
   * @return The ime.
   */
  java.lang.String getIme();
  /**
   * <code>string ime = 2;</code>
   * @return The bytes for ime.
   */
  com.google.protobuf.ByteString
      getImeBytes();

  /**
   * <code>int32 godina = 3;</code>
   * @return The godina.
   */
  int getGodina();
}
