// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package rs.raf.pds.v5.z2.gRPC;

/**
 * Protobuf type {@code StudentUpit}
 */
public final class StudentUpit extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:StudentUpit)
    StudentUpitOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StudentUpit.newBuilder() to construct.
  private StudentUpit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StudentUpit() {
    sifStud_ = "";
    ime_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StudentUpit();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rs.raf.pds.v5.z2.gRPC.StudentServiceOuterClass.internal_static_StudentUpit_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rs.raf.pds.v5.z2.gRPC.StudentServiceOuterClass.internal_static_StudentUpit_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rs.raf.pds.v5.z2.gRPC.StudentUpit.class, rs.raf.pds.v5.z2.gRPC.StudentUpit.Builder.class);
  }

  public static final int SIFSTUD_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sifStud_ = "";
  /**
   * <code>string sifStud = 1;</code>
   * @return The sifStud.
   */
  @java.lang.Override
  public java.lang.String getSifStud() {
    java.lang.Object ref = sifStud_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sifStud_ = s;
      return s;
    }
  }
  /**
   * <code>string sifStud = 1;</code>
   * @return The bytes for sifStud.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSifStudBytes() {
    java.lang.Object ref = sifStud_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sifStud_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ime_ = "";
  /**
   * <code>string ime = 2;</code>
   * @return The ime.
   */
  @java.lang.Override
  public java.lang.String getIme() {
    java.lang.Object ref = ime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ime_ = s;
      return s;
    }
  }
  /**
   * <code>string ime = 2;</code>
   * @return The bytes for ime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImeBytes() {
    java.lang.Object ref = ime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GODINA_FIELD_NUMBER = 3;
  private int godina_ = 0;
  /**
   * <code>int32 godina = 3;</code>
   * @return The godina.
   */
  @java.lang.Override
  public int getGodina() {
    return godina_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sifStud_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sifStud_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ime_);
    }
    if (godina_ != 0) {
      output.writeInt32(3, godina_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sifStud_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sifStud_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ime_);
    }
    if (godina_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, godina_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rs.raf.pds.v5.z2.gRPC.StudentUpit)) {
      return super.equals(obj);
    }
    rs.raf.pds.v5.z2.gRPC.StudentUpit other = (rs.raf.pds.v5.z2.gRPC.StudentUpit) obj;

    if (!getSifStud()
        .equals(other.getSifStud())) return false;
    if (!getIme()
        .equals(other.getIme())) return false;
    if (getGodina()
        != other.getGodina()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SIFSTUD_FIELD_NUMBER;
    hash = (53 * hash) + getSifStud().hashCode();
    hash = (37 * hash) + IME_FIELD_NUMBER;
    hash = (53 * hash) + getIme().hashCode();
    hash = (37 * hash) + GODINA_FIELD_NUMBER;
    hash = (53 * hash) + getGodina();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rs.raf.pds.v5.z2.gRPC.StudentUpit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.StudentUpit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.StudentUpit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.StudentUpit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.StudentUpit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.StudentUpit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.StudentUpit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.StudentUpit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.StudentUpit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.StudentUpit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.StudentUpit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.StudentUpit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rs.raf.pds.v5.z2.gRPC.StudentUpit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code StudentUpit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:StudentUpit)
      rs.raf.pds.v5.z2.gRPC.StudentUpitOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.raf.pds.v5.z2.gRPC.StudentServiceOuterClass.internal_static_StudentUpit_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.raf.pds.v5.z2.gRPC.StudentServiceOuterClass.internal_static_StudentUpit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.raf.pds.v5.z2.gRPC.StudentUpit.class, rs.raf.pds.v5.z2.gRPC.StudentUpit.Builder.class);
    }

    // Construct using rs.raf.pds.v5.z2.gRPC.StudentUpit.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sifStud_ = "";
      ime_ = "";
      godina_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rs.raf.pds.v5.z2.gRPC.StudentServiceOuterClass.internal_static_StudentUpit_descriptor;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.StudentUpit getDefaultInstanceForType() {
      return rs.raf.pds.v5.z2.gRPC.StudentUpit.getDefaultInstance();
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.StudentUpit build() {
      rs.raf.pds.v5.z2.gRPC.StudentUpit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.StudentUpit buildPartial() {
      rs.raf.pds.v5.z2.gRPC.StudentUpit result = new rs.raf.pds.v5.z2.gRPC.StudentUpit(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(rs.raf.pds.v5.z2.gRPC.StudentUpit result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sifStud_ = sifStud_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ime_ = ime_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.godina_ = godina_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rs.raf.pds.v5.z2.gRPC.StudentUpit) {
        return mergeFrom((rs.raf.pds.v5.z2.gRPC.StudentUpit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rs.raf.pds.v5.z2.gRPC.StudentUpit other) {
      if (other == rs.raf.pds.v5.z2.gRPC.StudentUpit.getDefaultInstance()) return this;
      if (!other.getSifStud().isEmpty()) {
        sifStud_ = other.sifStud_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getIme().isEmpty()) {
        ime_ = other.ime_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getGodina() != 0) {
        setGodina(other.getGodina());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sifStud_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              ime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              godina_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sifStud_ = "";
    /**
     * <code>string sifStud = 1;</code>
     * @return The sifStud.
     */
    public java.lang.String getSifStud() {
      java.lang.Object ref = sifStud_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sifStud_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sifStud = 1;</code>
     * @return The bytes for sifStud.
     */
    public com.google.protobuf.ByteString
        getSifStudBytes() {
      java.lang.Object ref = sifStud_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sifStud_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sifStud = 1;</code>
     * @param value The sifStud to set.
     * @return This builder for chaining.
     */
    public Builder setSifStud(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sifStud_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string sifStud = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSifStud() {
      sifStud_ = getDefaultInstance().getSifStud();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string sifStud = 1;</code>
     * @param value The bytes for sifStud to set.
     * @return This builder for chaining.
     */
    public Builder setSifStudBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sifStud_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object ime_ = "";
    /**
     * <code>string ime = 2;</code>
     * @return The ime.
     */
    public java.lang.String getIme() {
      java.lang.Object ref = ime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ime = 2;</code>
     * @return The bytes for ime.
     */
    public com.google.protobuf.ByteString
        getImeBytes() {
      java.lang.Object ref = ime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ime = 2;</code>
     * @param value The ime to set.
     * @return This builder for chaining.
     */
    public Builder setIme(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ime_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string ime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIme() {
      ime_ = getDefaultInstance().getIme();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string ime = 2;</code>
     * @param value The bytes for ime to set.
     * @return This builder for chaining.
     */
    public Builder setImeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ime_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int godina_ ;
    /**
     * <code>int32 godina = 3;</code>
     * @return The godina.
     */
    @java.lang.Override
    public int getGodina() {
      return godina_;
    }
    /**
     * <code>int32 godina = 3;</code>
     * @param value The godina to set.
     * @return This builder for chaining.
     */
    public Builder setGodina(int value) {

      godina_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 godina = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGodina() {
      bitField0_ = (bitField0_ & ~0x00000004);
      godina_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:StudentUpit)
  }

  // @@protoc_insertion_point(class_scope:StudentUpit)
  private static final rs.raf.pds.v5.z2.gRPC.StudentUpit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rs.raf.pds.v5.z2.gRPC.StudentUpit();
  }

  public static rs.raf.pds.v5.z2.gRPC.StudentUpit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StudentUpit>
      PARSER = new com.google.protobuf.AbstractParser<StudentUpit>() {
    @java.lang.Override
    public StudentUpit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StudentUpit> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StudentUpit> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.StudentUpit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

